<?php

// config/services.yaml
services:
    _defaults:
        autoconfigure: true
        autowire: true
        
    Arminfrey\ContaoPersonenBundle\EventListener\ContaoPersonenListener:
        tags:
            - { name: contao.hook, hook: getSystemMessages }
    
    Arminfrey\ContaoPersonenBundle\Controller\ContaoPersonenController:
        arguments:
            - '@database_connection'
        tags:
            - { name: controller.service_arguments }
    
    Arminfrey\ContaoPersonenBundle\Migration\ContaoPersonenMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }
